version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "Rockstar@45"
      MYSQL_DATABASE: ssvm
      MYSQL_USER: appuser
      MYSQL_PASSWORD: "Rockstar@45"
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u appuser -p$MYSQL_PASSWORD" ]
      interval: 10s
      timeout: 5s
      retries: 5

  springboot-app:
    build: ./
    container_name: springboot-app
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql:///ssvm \
?cloudSqlInstance=springboot-gcp-demo-484016:asia-south1:my-mysql \
&socketFactory=com.google.cloud.sql.mysql.SocketFactory
      SPRING_DATASOURCE_USERNAME: appuser
      SPRING_DATASOURCE_PASSWORD: "Rockstar@45"
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  mysql_data:
